export enum IpcEvents {
  WIN_INVOKE = "win:invoke",
  WIN_MAX_REPLY = "win:max-reply",
  EV_SHOW_OPEN_DIALOG = "ev:show-open-dialog",
  EV_ADD_VIDEOS = "ev:add-videos",
  EV_GET_PLAYLIST = "ev:get-playlist",
  EV_PLAY = "ev:play",
  EV_PAUSE = "ev:pause",
  PC_TEST = "pc:test",
  PC_WINDOW_OPERATE = "pc:window-op",
  PC_VIEW_CREATE = "pc:view-create",
  PC_VIEW_SELECT = "pc:view-select",
  PC_VIEW_F12 = "pc:view-f12",
  PC_OPEN_DIALOG = "OpenLocalFile",
}
